trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  imageName: 'pipelines-javascript-docker'

steps:
- task: HelmInstaller@0
  inputs:
    helmVersion: '3.0.0'
    installKubectl: true
  displayName: Installing helm

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'compile'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Commpling  Package'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'install'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
  displayName: 'Installing Package'

- task: CmdLine@2
  inputs:
    script: 'ls'
    workingDirectory: 'target'
  displayName: 'Viewing Directory Structure'
  
- script: |
    cd target
    ls
  displayName: 'Just Viewing directory structure'
  
- task: Docker@2
  inputs:
    command: build
    repository: $(imageName)
    Dockerfile: Dockerfile
  displayName: 'Building Image'


- script: |
    sudo docker images
  displayName: 'Display Docker Images'
